config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'events#index'
  resources :users, only: %i[show]
  resources :event_attendances, only: %i[new create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :event_attendances, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :event_attendances

  validates :date, :time, :location, :description, :title, presence: true
  validate :date_cannot_be_in_the_past, :time_cannot_be_in_the_past
  validates :title, length: { in: 10..60 }
  validates :description, length: { maximum: 512 }

  scope :past, -> { where('date < ?', Date.today) }

  scope :upcoming, -> { where('date >= ?', Date.today) }

  def date_cannot_be_in_the_past
    if date.present? && date < Date.today
      errors.add(:date, 'can\'t be in the past')
    end
  end

  def time_cannot_be_in_the_past
    unless date_cannot_be_in_the_past
      if time.present? && time < Time.now
        errors.add(:time, 'can\'t be in the past')
      end
    end
  end
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: 'creator', class_name: 'Event', dependent: :destroy
  has_many :event_attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController
  before_action :authenticate_user!

  def new
    @event_attendance = EventAttendance.new
  end

  def create
    event = Event.find(params[:attended_event_id])
    @event_attendance = EventAttendance.new(
      attendee_id: current_user.id,
      attended_event_id: event.id
    )
    if @event_attendance.save
      flash[:notice] = "Sucessfully Attended"
      redirect_to event_path(event)
    else
      flash.now[:alert] = 'Woo Something bad Happened.'
      render event_path(event)
    end
  end


  def destroy
    @event_attendance = EventAttendance.find(params[:id])
    @event_attendance.destroy
    flash[:notice] = 'You have successfully unattended the event'
    redirect_back fallback_location: root_path
  end

  private

  def event_attendance_params
    params.permit(:attended_event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[index show]
  # GET /events or /events.json
  def index
    @past_events = Event.past
    @upcoming_events = Event.upcoming
  end

  # GET /events/1 or /events/1.json
  def show
    @event = Event.includes(:attendees).find(params[:id])
  end

  # GET /events/new
  def new
    @event = current_user.created_events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.created_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        flash.now[:alert] = 'Event could not be saved, see errors.'
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:date, :time, :location, :title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.includes(:attended_events).find(current_user.id)
    @user_events = @user.created_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_attendance.html.erb
<%= form_with url: event_attendances_path do |f| %>
    <%= f.hidden_field :attended_event_id, value: @event.id %>
    <%= f.submit 'Attend', class: "button is-success has-text-weight-medium" %>
<% end %>

app/views/events/_event.html.erb
<div class="column is-one-quarter">
    <div class="card">
        <header class="card-header">
            <p class="card-header-title is-centered">
                <%= event.title %>
            </p>
        </header>

        <div class="card-content event-card has-text-centered">
            <div class="content">
                <%= event.description %>
            </div>
            <%= event.date.strftime('%a %b %d %Y') %> | <%= event.time.strftime('%H:%M')%>
        </div>
    <footer class="card-footer">
        <a href="<%= event_path(event)%>" class="card-footer-item">Details</a>
    </footer>
    </div>
</div>

app/views/events/_form.html.erb
<% if @event.errors.any? %>
  <div class="notification is-warning" id="error_explanation">
    <h2 class="title is-4">Your event contains <%= pluralize(@event.errors.count, "error") %></h2>

    <ul>
      <% @event.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with model: @event do |f| %>
  <div class="field">
    <%= f.label :title, 'Your event\'s title: ', class: 'label' %>
    <div class="control">
        <%= f.text_field :title, class: 'input'%>
    </div>
  </div>

  <div class="field">
    <%= f.label :description, 'Describe your event', class: 'label' %>
    <div class="control">
        <%= f.text_area :description, class: 'input'%>
    </div>
  </div>

  <div class="field">
    <%= f.label :location, 'Your event\'s Location: ', class: 'label' %>
    <div class="control">
        <%= f.text_field :location, class: 'input'%>
    </div>
  </div>

  <div class="field">
    <%= f.label :date, 'Your event\'s date: ', class: 'label'%>
    <div class="control">
    <%= f.date_select :date, class:'select' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :time, 'Your event\'s time: ', class: 'label'%>
    <div class="control">
    <%= f.time_select :time, class:'input' %>
    </div>
  </div>

    <div class="level">
      <div class="level-item is-justify-content-flex-end">
        <%= f.submit :Create, class: "button is-danger has-text-weight-medium" %>
      </div>
  </div>
<% end %>

app/views/events/_unattend.html.erb
<% attendance = EventAttendance.find_by(attendee_id: current_user.id, attended_event_id: @event.id) %>
<%= link_to 'Unattend', event_attendance_path(attendance), data: { method: :delete }, class: "button is-warning has-text-weight-medium" %> 

app/views/events/edit.html.erb
<section class="section">
<div class="container">
    <div class="columns is-centered">
        <div class="column is-6 box">
            <h1 class='title has-text-centered'>Editing Event</h1>
            <%= render 'form', event: @event %>
            <%= link_to 'Show', @event %> |
            <%= link_to 'Back', events_path %>
        </div>
        </div>
    </div>
</section>

app/views/events/index.html.erb
<section class="hero is-primary is-fullheight-with-navbar">
</section>
</div>
<div class="section">
  <div class="container">
    <h2 id='upcoming' class='title has-text-centered'> Upcoming Events</h1>
    <div class="columns">
      <%= render partial: 'event', collection: @upcoming_events, as: :event %>
    </div>
    <h2 id='upcoming' class='title has-text-centered'> Past Events</h1>
    <div class="columns">
      <%= render partial: 'event', collection: @past_events, as: :event %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<section class="section">
<div class="container">
    <div class="columns is-centered">
        <div class="column is-6 box">
            <%= render 'form', event: @event %>
        </div>
    </div>
<%= link_to 'Back', events_path %>
</div>
</section>

app/views/events/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <div class="card">
          <header class="card-header">
              <p class="card-header-title is-centered">
                  <%= @event.title %>
              </p>
          </header>

          <div class="card-content">
              <div class="content">
                  <%= @event.description %><br/>
                  <small><%= @event.date.strftime('%a %b %d %Y')%> | <%= @event.time.strftime('%H:%M')%></small><br/>
              </div>
          </div>
          <% if user_signed_in? %>
          <div class="level">
            <div class="level-item is-justify-content-flex-center">
              <% unless @event.attendees.include?(current_user) %>
                <%= render 'attendance' %>
              <% else %>
                <%= render 'unattend' %>
              <% end %>
            </div>
          </div>
          
              <div class="card-footer">
            <% if current_user.id == @event.creator_id %>
                <%= link_to 'Edit', edit_event_path(@event), class: 'card-footer-item button is-link is-inverted' %>
                <%= link_to 'Delete', event_path(@event),
                    data: { method: :delete },
                    class: 'card-footer-item button is-link is-inverted'
                %>
            <% end %>
              </div>
          <% end %>
      </div>
    </div>

  </div>
    <div class="columns is-centered">
      <div class="column is-6">
        <div class="box">
          <h3 class='title is-4 has-text-centered'> Attendees List </h3>
          <% @event.attendees.each do |attendee| %>
              <p>
                <%= attendee.email %>
              </p>
          <% end %>
        </div>
        </div>
      </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
    <div class="notification is-primary global-notification has-text-centered has-text-weight-medium">
      <p class="notice"><%= notice %></p>
    </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification has-text-centered has-text-weight-medium">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
        <!-- nav bar -->
    <nav class="navbar is-danger is-mobile is-marginless">
      <div class="navbar-brand">
          <div class="navbar-item">
            <a href="<%= root_path %>">
              <h1 class="title">
                  Private Events
              </h1> 
            </a>
          </div>
          <div class="navbar-burger" id="burger">
              <span></span>
              <span></span>
              <span></span>
          </div>
      </div>
      <div class="navbar-menu" id="nav-links">
          <div class="navbar-end">
            <div class="navbar-item">
              <a  class='button is-black is-outlined' href="<%= events_path %>">
                Events
              </a>
            </div>
              <div class="buttons has-text-weight-bold navbar-item">
                <% if user_signed_in? %>
                  <%= link_to 'My Profile', user_path(current_user), class: 'button is-black is-outlined'%>
                  <%= link_to 'New Event', new_event_path, class: 'button is-black'%>
                  <%= link_to 'Sign out',destroy_user_session_path,  method: :delete , class: 'button is-danger' %>
                <% else %>
                  <%= link_to 'Login', new_user_session_path, class: 'button'%>
                  <%= link_to 'Sign up', new_user_registration_path, class: 'button is-danger' %>
                <% end %>
                </div>
          </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/_panel.html.erb
<div class='notification is-danger is-light'>
    <h3 class='subtitle'><%= event.title %></h3>
    <p class="content">
        <%= event.description %>
    </p>
    <small><%= event.location %></small> <br/>

    <small><%= event.date.strftime('%a %b %d %Y')%> | <%= event.time.strftime('%H:%M')%></small><br/>
    <%= link_to 'See more info', event_path(event) %>
</div>

app/views/users/show.html.erb
<section class="section">
    <div class="container">
        <div class="columns">

            <div class="column is-one-quarter">
                <div class="card">
                    <div class="card-header">
                        <p class="card-header-title">
                        <%= @user.email %>
                        </p>
                        <figure class="image card-header-icon">
                            <img class="is-rounded is64x64" src="https://bulma.io/images/placeholders/64x64.png" alt="Placeholder image">
                        </figure>
                    </div>
                </div>
            </div>


            
            <div class="column is-one-quarter">
                <div class="box has-text-centered">
                    <h2 class='title'>Created Events</h2>
                    <%= render(partial: 'panel', collection: @user_events, as: :event) || 'No Events to display' %>
                </div>
            </div>

            <div class="column is-one-quarter">
                <div class="box has-text-centered">
                    <h2 class='title'>Future Events</h2>
                    <% future_events =  @user.attended_events.filter {|e| e.date >= Date.today } %>
                    <%= render(partial: 'panel', collection: future_events, as: :event) || 'No Events to display' %>
                </div>
            </div>

            <div class="column is-one-quarter">
                <div class="box has-text-centered">
                    <h2 class='title'>Past Events</h2>
                    <% past_events = @user.attended_events.filter {|e| e.date < Date.today } %>
                    <%= render(partial: 'panel', collection: past_events, as: :event) || 'No Events to display' %>
                </div>
            </div>

        </div>
    </div>
</section>